package com.cooksys.twitterly.models;

// Generated Apr 28, 2016 6:40:49 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TweetId generated by hbm2java
 */
@Embeddable
public class TweetId implements java.io.Serializable
{

	private int tweetId;
	private int userId;

	public TweetId()
	{
	}

	public TweetId(int tweetId, int userId)
	{
		this.tweetId = tweetId;
		this.userId = userId;
	}

	@Column(name = "tweet_id", nullable = false)
	public int getTweetId()
	{
		return this.tweetId;
	}

	public void setTweetId(int tweetId)
	{
		this.tweetId = tweetId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId()
	{
		return this.userId;
	}

	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TweetId))
			return false;
		TweetId castOther = (TweetId) other;

		return (this.getTweetId() == castOther.getTweetId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getTweetId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
